version: '2'
services:

  gotham:
    build:
      context: .
      dockerfile: ./docker/perconaWithConsul.dockerfile
    volumes:
      - ./docker/gotham.cnf:/etc/mysql/conf.d/gotham.cnf
      - ./docker/consul_gotham_master.json:/etc/consul_config/consul_gotham_master.json
      - ./docker/consul_client_mdw.json:/etc/consul_config/config.json
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    expose:
      - "3306"
      - "8400"
      - "8500"
      - "8501"
      - "8600"

  gotham2:
    build:
      context: .
      dockerfile: ./docker/perconaWithConsul.dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./docker/gotham_repl.cnf:/etc/mysql/conf.d/gotham_repl.cnf
      - ./docker/consul_gotham_replica.json:/etc/consul_config/consul_gotham_replica.json
      - ./docker/consul_server_mdw.json:/etc/consul_config/config.json
    links:
      - gotham
    expose:
      - "3306"
      - "8400"
      - "8500"
      - "8501"
      - "8600"
    ports:
      - "8500:8500"
      - "8600:8600"
      - "3306:3306"

  gotham3:
    build:
      context: .
      dockerfile: ./docker/perconaWithConsul.dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./docker/gotham_repl.cnf:/etc/mysql/conf.d/gotham_repl.cnf
      - ./docker/consul_gotham_replica.json:/etc/consul_config/consul_gotham_replica.json
      - ./docker/consul_client_mdw.json:/etc/consul_config/config.json
    links:
      - gotham2
    expose:
      - "3306"
      - "8400"
      - "8500"
      - "8501"
      - "8600"

  gotham_las:
    build:
      context: .
      dockerfile: ./docker/perconaWithConsul.dockerfile
    volumes:
      - ./docker/gotham.cnf:/etc/mysql/conf.d/gotham.cnf
      - ./docker/consul_gotham_master.json:/etc/consul_config/consul_gotham_master.json
      - ./docker/consul_server_las.json:/etc/consul_config/config.json
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    links:
      - gotham2
    expose:
      - "3306"
      - "8400"
      - "8500"
      - "8501"
      - "8600"

  newyork:
    image: percona:5.7
    volumes:
      - ./docker/newyork.sql:/etc/newyork.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    expose:
      - "3306"

  proxysql:
    build:
      context: .
      dockerfile: ./docker/psql1.4.7.dockerfile
    volumes:
      - ./docker/proxysql.cnf:/etc/proxysql.cnf
      # - ./data:/var/lib/proxysql
    links:
      - gotham
      - newyork
      - gotham2
      - gotham3
    ports:
      - "6032:6032"
      - "6033:6033"
    expose:
      - "6032"
      - "6033"
    command: >
      bash -c "/usr/bin/proxysql -f -c /etc/proxysql.cnf --initial 2>&1 | tee -a /var/lib/proxysql/proxysql.log"

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "8081:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  devel:
    build:
      context: .
      dockerfile: ./docker/devel.dockerfile
    volumes:
      - ./docker/users.sql:/etc/users.sql
      - ./docker/gotham.sql:/etc/gotham.sql
      - ./docker/newyork.sql:/etc/newyork.sql
      - ./docker/devel.sh:/etc/devel.sh
    links:
      - gotham
      - newyork
      - proxysql
      - graphite
      - gotham2
      - gotham3
      - gotham_las
    command: >
      bash /etc/devel.sh
