version: '2'
services:

  # mysql:
  #   image: percona:5.7
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"

  # mysql_02:
  #   image: percona:5.7
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
  #   expose:
  #     - "33062"
  #   ports:
  #     - "33062:33062"

  # mysql_03:
  #   image: percona:5.7
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
  #   expose:
  #     - "33063"
  #   ports:
  #     - "33063:33063"

  gotham:
    image: percona:5.7
    volumes:
      - ./docker/gotham.sql:/etc/gotham.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    expose:
      - "3306"

  newyork:
    image: percona:5.7
    volumes:
      - ./docker/newyork.sql:/etc/newyork.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    expose:
      - "3306"

  proxysql:
    build:
      context: .
      dockerfile: ./docker/psql1.4.7.dockerfile
    volumes:
      - ./docker/proxysql.cnf:/etc/proxysql.cnf
      # - ./data:/var/lib/proxysql
    links:
      - gotham
      - newyork
    ports:
      - "6032:6032"
      - "6033:6033"
    expose:
      - "6032"
      - "6033"
    command: >
      bash -c "/usr/bin/proxysql -f -c /etc/proxysql.cnf --initial 2>&1 | tee -a /var/lib/proxysql/proxysql.log"

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "8081:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  devel:
    build:
      context: .
      dockerfile: ./docker/devel.dockerfile
    volumes:
      - ./docker/gotham.sql:/etc/gotham.sql
      - ./docker/newyork.sql:/etc/newyork.sql
    links:
      - gotham
      - newyork
      - proxysql
      - graphite
    command: >
      bash -c "
      while ! echo | nc -w1 gotham 3306 > /dev/null ; do printf 'waiting for gotham: '; sleep 1; done; echo gotham connected &&
      mysql -uroot -h gotham < /etc/gotham.sql &&
      while ! echo | nc -w1 newyork 3306 > /dev/null ; do printf 'waiting for newyork: '; sleep 1; done; echo newyork connected &&
      mysql -uroot -h newyork < /etc/newyork.sql &&
      while ! echo | nc -w1 proxysql 6032 > /dev/null ; do printf 'waiting for proxysql: '; sleep 1; done; echo proxysql connected &&
      echo devel ready"
